### ISSUE TITLE
make power consumption collection optional

### ISSUE THREAD

**Issue by propertone** [soundcloud/ipmi_exporter#1]
Thanks for creating this exporter! Some hardware (eg: Cisco) does not appear to support the ipmi dcmi extension, so the ipmi-dcmi command fails with:
`ipmi_cmd_dcmi_get_power_reading: command invalid or unsupported`

Can you make it so that the collector still collects the monitoring data even if the dcmi command fails?

Some ideas:

- Add a flag to disable ipmi-dcmi
- Add ipmi_dcmi_up metric to indicate whether dcmi command succeeded, and proceed even if it fails.
- Run ipmimonitoring before ipmi-dcmi, and set ipmi_up to 0 only if bmc-info or ipmimonitoring commands fail
- Detect whether DCMI is supported before running the ipmi-dcmi command (not sure how to do that).

**Comment by bitfehler** [comment]
@propertone this should be fixed with https://github.com/soundcloud/ipmi_exporter/commit/109c7ca99c63f15b632afbdc38b121438ee7fc9d, with more improvements around this to be coming a little later. Can you confirm that this at least makes it work for you?

**Comment by RajKiranS** [comment]
@bitfehler , On behalf of @propertone, I confirm that its working as expected. The DCMI is being skipped wherever it has problems and rest of the metrics are queried. Thanks much!

**Comment by bitfehler** [comment]
Great to hear, thanks! More fine-grained control over this will be added later on.

**Comment by SmileNil** [comment]
When I use ipmi exporter to obtain information about Huawei physical machines, having a error: ipmi_cmd_dcmi_get_power_reading: command invalid or unsupported is displayed. What can I do?
`[root@server ~]# ipmi-dcmi -h 10.0.0.23 -u ADMIN -P -D LAN_2_0 --get-power-limit
Password:
ipmi_cmd_dcmi_get_power_limit: command invalid or unsupported
`

**Comment by sachasmart** [comment]
Any solution to this. Currently running into this

```bash
ipmi-dcmi --get-system-power-statistics
ipmi_cmd_dcmi_get_power_reading: command invalid or unsupported
```

**Comment by bitfehler** [comment]
Apparently the hardware doesn't support it. If you are absolutely sure that it does, it would be an issue with FreeIPMI, not this exporter.
