### ISSUE TITLE
Can we drop the privilege-level to user by default

### ISSUE THREAD

**Issue by RajKiranS** [soundcloud/ipmi_exporter#10]
I see that in the base freeipmiconfig, the privilege-level is hardcoded to "admin".
```
func freeipmiConfig(driver, user, password string) string {
	return fmt.Sprintf(`
driver-type %s
privilege-level admin
```
Is there any specific reason to default to "admin" level here? I changed to "user" level and could fetch the same metrics as when it was set to "admin" level. (PS. I couldn't test ipmi_cmd_dcmi_get_power_reading as its unsupported on my test box). But, I guess that should work too!

The reason I am bringing this up is because, we want to create a separate user for monitoring with a lesser privilege level.

Also, when the privilege-level is lowered here, higher privileged users can connect but not vise-versa. So, couple of options I can think of:
1. By default, set the privilege-level to user.
2. Provide a config option to set privilege-level.

**Comment by bitfehler** [comment]
Hi there!
Thanks for the report, you are certainly very right. The main reason for this being this way is lousy hardware we had to deal with, but it certainly shouldn't be the default for everyone. I'll make this configurable.

**Comment by matejzero** [comment]
This would be nice to have, so I can give RO user to ipmi_exporter.

**Comment by matejzero** [comment]
It seems to me I have the same problems as bitfehler has:)

Lenovo x35X0 servers work with `user` privilege, but needs `LAN` driver, but Lenovo SR6XX servers only work with `admin` privileges and need `LAN_2_0` driver. So I guess I won't benefit from this fix:)

Meh.

**Comment by matejzero** [comment]
After some more work on the subject I got everything working.

The culprit was an old `freeipmi` package which was part of my OS's repository. With latest freeipmi, I can pull info via `IPMI 2.0` for all my servers with `user` level permissions.

Sorry for the noise.

**Comment by SuperQ** [comment]
@matejzero Can you share which specific versions? We should add minimum version recommendations and/or checks to the code/docs.

**Comment by matejzero** [comment]
I was using `1.2.1` from CentOS 6 and that didn't work. Now I'm using `1.6.2` which I build from source and it's working nicely.
