### ISSUE TITLE
Can we have releases of this exporter

### ISSUE THREAD

**Issue by RajKiranS** [soundcloud/ipmi_exporter#24]
Hello,

Can we add version info and metadata to the exporter. And then tag/release it accordingly? Similar to other Prometheus exporters out there.

I am asking so that we can push out this to NixPkgs and download/install it from there. Or in general for any in-house packaging and maintenance.

Thanks,
Raj

**Comment by bitfehler** [comment]
Hi Raj,
thanks for raising this. We initially decided against this, as this was still a very young project and we weren't quite sure where things were going. I think with the config refactoring in place it might be a good time to re-evaluate, however. Please give us a bit more time to think this through.

Out of curiosity, I have one question though: is it not possible for Nix to deal with git-based versioning? In-house, we sometimes use versions like `echo "$(git rev-list --count master)-$(git rev-parse --short HEAD)"`, which gives you something like `27-11f3809`, where the first number will increase monotonically and the second indicates the git commit hash.

**Comment by bitfehler** [comment]
https://github.com/soundcloud/ipmi_exporter/releases :tada:
