### ISSUE TITLE
Which options are supported  for the driver setting？

### ISSUE THREAD

**Issue by luyuanx2** [soundcloud/ipmi_exporter#26]
I command through "man 5 freeipmi.conf" , there is no options:
    driver-type IPMIDRIVER
    Specify the default driver type to use.

**Comment by bitfehler** [comment]
Hi there!

Thanks for reporting this. The available options are indeed not listed there. To see the available options, please see `man 8 ipmi-sensors` (also installed by FreeIPMI) instead. Look for the `--driver-type=IPMIDRIVER` option. The listed values for `IPMIDRIVER` are the same that you can use in the config file.

I forgot to mention this issue in the commit message, but I added a pointer to the example config in https://github.com/soundcloud/ipmi_exporter/commit/e2ddbbf31c3e4b4ef48e0103ad728528eaa55480, which I hope should take care of this. I will close this issue, but if you feel there is still something missing, please feel free to keep commenting on this issue.
