### ISSUE TITLE
Collect IPMI metrics locally per node?

### ISSUE THREAD

**Issue by jmreicha** [soundcloud/ipmi_exporter#3]
The main use case that I would like to use this exporter for would be to collect IPMI metrics locally for each node, similar to the approach that https://github.com/lovoo/ipmi_exporter takes and similar to how node-exporter works.

Is this behavior possible with this exporter?

**Comment by SuperQ** [comment]
This exporter is designed to work as a proxy, remotely over the network, rather than locally. More similar to the snmp or blackbox exporters.

**Comment by bitfehler** [comment]
Hi @jmreicha, this should now be possible with the latest version. Since we don't use this in production it would be great to get feedback if this meets your use case now.

**Comment by jmreicha** [comment]
Sorry, haven't had much time lately to test this.  I can open a new issue if it doesn't work.
