### ISSUE TITLE
Stale named pipes left behind in /tmp

### ISSUE THREAD

**Issue by dswarbrick** [soundcloud/ipmi_exporter#42]
I noticed after running the exporter for a few weeks, configured to probe several hundred remote hosts, that stale named pipes are being left behind in /tmp.

Looking at the `freeipmiOutput` function, I see there is a deferred `os.Remove` of the pipe, so this _should_ be removing the pipe, even if the command execution fails. Obviously however, sometimes the named pipes are not being removed.

In the `freeipmiConfigPipe` function that creates the named pipes, I see there is a goroutine which actually writes the config to the pipe. AFAICT, the reason why this is a goroutine is that writing to a pipe will block until something reads from the pipe (i.e., when the ipmitool command is executed).

`lsof` doesn't appear to indicate that the exporter is leaking FDs, so the "bug" seems to be somewhere in the code _after_ the config is written to the pipe and the FD has been closed. Indeed, trying to read from the pipe simply blocks, which indicates that content has already been read from it (i.e., by ipmitool).

**Comment by bitfehler** [comment]
Oh my. Thanks for the report, I can confirm that I also do see this. The amount of stale pipes I see on our servers is relatively low, given their uptime and scrape frequency, so I have a hunch that this will not be easily reproducible, so potentially hard to debug. I'll give it a try, though.

**Comment by dswarbrick** [comment]
The timestamps on the stale pipes suggest that it doesn't occur regularly. On a couple of systems I see quite a large number of stale entries on just two separate days back in December. On one of those systems, I restarted the exporter, and can see about ten stale entries from an hour ago, but nothing more recent than that. So it's definitely intermittent, and the instances of "leaking" seem to be clustered together.

**Comment by bitfehler** [comment]
Interesting. We run the IPMI exporter on two different servers for redundancy, but active-active. I updated IPMI exporter on both on Feb 23rd. They both did not leak any pipes until March 5th, when _both_ leaked pipes at _two different_ points in time, all lining up nicely. So I suspect that external forces might be involved (network failure?)...

**Comment by bitfehler** [comment]
@dswarbrick can you let me know if this is still happening for you on the latest version? It almost seems like this is not happening for us anymore, but it is of course hard to say without knowing what actually triggered this...

**Comment by dswarbrick** [comment]
@bitfehler I just checked our ~10 instances, and none of them has any stale pipes.

I'm happy if you want to close this.

**Comment by bitfehler** [comment]
Cool. Will assume that it was a problem with the library used here, do let me know if it ever shows up again.

**Comment by schloegl** [comment]
We see this as well on regular basis. Eventually it fills up /tmp  
```
# ls -altr /tmp/ipmi_exporter-*
---------- 1 root root 22 Dec  3 08:41 /tmp/ipmi_exporter-c098143e468349f5e09189e5006ef575
---------- 1 root root 22 Dec  3 08:41 /tmp/ipmi_exporter-1fab3fa6a65b80f174670fa033f6c0c9
---------- 1 root root 22 Dec  3 11:21 /tmp/ipmi_exporter-fd7585e3f9bc4ee8da7204b23219b66d
---------- 1 root root 22 Dec  3 11:40 /tmp/ipmi_exporter-c0d9c08398ffcbcdc5dd6333c16ab65f
---------- 1 root root 22 Dec  3 14:19 /tmp/ipmi_exporter-38cfedd448fd4a5b6e3428ce7aad7202
---------- 1 root root 22 Dec  3 14:19 /tmp/ipmi_exporter-1df0ed3abea62d7840cadea954b6ba41
... 


```The content of these files is always 
```
# cat /tmp/ipmi_exporter-fd7585e3f9bc4ee8da7204b23219b66d 
privilege-level admin

```

In order to mitigate the problem of filling up /tmp, we are deleting these on a a regular basis. But this is not a proper solutions. 


The manual about pipes  [1] has a section on "bugs"
ulimit is set in our set up to 
pipe size                (512 bytes, -p) 8

Could this be a possible explaination ? 

Do you have some suggestions how to debug and fix this issue ? 



 [1]  https://man7.org/linux/man-pages/man7/pipe.7.html
