### ISSUE TITLE
Documentation bug?

### ISSUE THREAD

**Issue by misterbaldi** [soundcloud/ipmi_exporter#43]
Hi,
maybe i do something wrong or maybe a documentation bug:
my config in prometheus.yml

  - job_name: ipmi
    params:
     module: default
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /ipmi
    scheme: http
    file_sd_configs:
    - files:
      - /data/prometheus/targets/targets_ipmi_exporter.yml
      refresh_interval: 5m
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: __param_target
      replacement: ${1}
      action: replace
    - source_labels: [__param_target]
      separator: ;
      regex: (.*)
      target_label: instance
      replacement: ${1}
      action: replace
    - separator: ;
      regex: .*
      target_label: __address__
      replacement: localhost:9290
      action: replace

1. module: default -> shuld look like module: [default]?
failed to reload config: couldn't load configuration (--config.file="/etc/prometheus/prometheus.yml"): parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:
  line 38: cannot unmarshal !!str `default` into []string

2. config from https://github.com/soundcloud/ipmi_exporter/blob/master/ipmi_remote.yml
sysadmin@prometheus01:bin$ sudo ./ipmi_exporter --config.file=/etc/prometheus/ipmi_exporter.yml
INFO[0000] Starting ipmi_exporter                        source="main.go:83"
FATA[0000] Error parsing config file: unknown fields in modules: workaround_flags  source="main.go:87"

**Comment by bitfehler** [comment]
Hi!
Is it possible that you are running the 1.0 release? The `workaround_flags` are only on the current master branch, they are not in a released version yet.

**Comment by bitfehler** [comment]
Hey everyone,
I released version 1.1.0 today, mostly to avoid exactly this confusion about a mismatch of the documentation to the latest release. Please upgrade at your earliest convenience, not much else has changed so you should not run into any problems. I am closing this, but feel free to reopen if anything is still wrong.
