### ISSUE TITLE
New metric for lan mode?

### ISSUE THREAD

**Issue by frenkye** [soundcloud/ipmi_exporter#47]
Hi,

first thank you for maintaining this exporter, it is great.

In our case we find out, we had some issue with default network lan mode ("failover"). The problem was when IPMI dedicated link was down IPMI switched to shared iface (server uplink). We use diffent VLANs for IPMI and uplinks, so that is a bit problem, because its stoped working until manual change from the server. We are trying to avoid this by setting that to dedicated from failover and monitor wanted state.

More on this can be read here [ServerFault](https://serverfault.com/questions/361940/configuring-supermicro-ipmi-to-use-one-of-the-lan-interfaces-instead-of-the-ipmi)

For this we had monitoring using `ipmitool` and tracking output `ipmitool raw 0x30 0x70 0x0c 0`

This can be done with:
`/usr/sbin/ipmi-raw 0x0 0x30 0x70 0x0c 0` - which is tool from freeipmi pkg.
It result into:
* `rcvd: 70 00 00` - dedicated
* `rcvd: 70 00 01` - shared
* `rcvd: 70 00 02` - failover

With metric something like:
```
# Help ipmi_config_lan_mode Return lan mode status (0=dedicated, 1=shared, 2=failover)
# Type ipmi_config_lan_mode gauge
ipmi_config_lan_mode 0
```

Do you think this could be implemented?

**Comment by bitfehler** [comment]
Uh boy, `ipmi-raw`! I was wondering when things might go that way :wink: 

Jokes aside, though, first of all thanks a lot for providing a thoroughly detailed suggestion. This is certainly something that would make for a good metric. If I understand the ServerFault thread correctly, this is a Supermicro-specific OEM extension though, right?

As it stands, this could be made an additional, optional collector. Also, I have `ipmi-raw` on my list anyways, as it would probably make for the ultimate generic extension mechanism, but I have not yet spent much time on thinking about how best implement this (providing interfaces is always tricky, for they are harder to change). Give me some time to look into this, but I see a good chance that this will be possible one way or another eventually.

**Comment by frenkye** [comment]
I understand the thoughts about `ipmi-raw`. IMO would be better if this was shown like under `ipmi-config` or something like that, since it's under config->network section in GUI.

About Supermicro-specific OEM extension. I just looked it up and seems like Supermicro is one that is left out . When i run `ipmi-oem` most of them got command `get-nic-mode`, but not supermicro. I just check even unstable pkgs for debian and there is no update either.

Separate module would be great for this, because setting that up, could be really tricky and it could done more harm than good if not set properly. Since one typo could mean `set` instead of `get`.
