### ISSUE TITLE
ipmi cache

### ISSUE THREAD

**Issue by bobykus31** [soundcloud/ipmi_exporter#48]
Is there any way to control the sdr cache? With some latest kernels ipmi tools oftenly refuse  to   output data because of memory issue.  Like

:~# ipmi-sel 
ipmi_ctx_find_inband: out of memory

Seems to be related to 

https://lkml.org/lkml/2020/4/17/16

**Comment by bitfehler** [comment]
No, not at the moment. What specifically would you need to do to work around this?

**Comment by bitfehler** [comment]
Closing, as I assume it is no longer an issue. Reopen if needed.
