### ISSUE TITLE
collect metrics from "bmc getsysinfo system_fw_version"

### ISSUE THREAD

**Issue by ainamori** [soundcloud/ipmi_exporter#51]
Hi, I'd like to collect the BIOS version from IPMI.
I tried to add code by myself.
However, I am not familiar with golang so that but I couldn't make packages.
Could you add the feature please ?

##### ISSUE TYPE
 - Enhanced

##### HOW TO GET THE INFO
 ipmitool bmc getsysinfo system_fw_version
 
##### SAMPLE COMMAND OUTPUT

```bash
 $ ipmitool -H <target host> -I lanplus -U <user> -P <password> bmc getsysinfo system_fw_version
  Version1.0
```
In most cases, the return value is "strings". not integer.

##### METRICS EXAMPLE

```
# HELP ipmi_bmc_sysinfo Constant metric with value '1' providing details about the BMC.
# TYPE ipmi_bmc_sysinfo gauge
ipmi_bmc_sysinfo{system_fw_version="Version 1.0"} 1
```

**Comment by ainamori** [comment]
Or, could you check my code and teach me how to modify the code please ?

https://github.com/soundcloud/ipmi_exporter/pull/52

**Comment by bitfehler** [comment]
Hi, thanks for the request, this seems like good information to export. It can actually be done much simpler than in the PR you provided. I will take a look at this in the next days.

**Comment by bitfehler** [comment]
Hey there,
sorry, not exactly "the next days", but you know... So, this is now on master, if you can run that I'd be happy to hear if it works for you. I'll also prepare the next release soon, but there are a few more things I'd like to add before that.

**Comment by ainamori** [comment]
Hi, I'm sorry for too late reply.
I found that it work well. thank you so much!

**Comment by ainamori** [comment]
I'm sorry for too late reply.
I found the new key in latest version.
However, It shows as below ,even `bmc getsysinfo system_fw_version` works well.

```
ipmi_bmc_info{firmware_revision="x.xx",manufacturer_id="Our vender name.",system_firmware_version=""} 1
```

I'll check our systems and I'll open the Issue in case I found the cause in codes.
Thank you so much!
