### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by mo254** [soundcloud/ipmi_exporter#55]
Hey,
after setting go environment when i start 'make' a receive the following:
>> checking code style
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
go: downloading github.com/prometheus/common v0.10.0
go: downloading github.com/prometheus/client_golang v1.7.1
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: downloading github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d
go: downloading github.com/stretchr/testify v1.5.1
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading golang.org/x/sys v0.0.0-20200724161237-0e2f3a69832c
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/prometheus/procfs v0.1.3
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.3
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/google/go-cmp v0.5.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Makefile.common:212: recipe for target 'common-unused' failed
make: *** [common-unused] Error 129

can you please help me

**Comment by bitfehler** [comment]
Hm, I am not quite sure what's going on there. Can you try with a completely clean `GOPATH` (i.e. create an empty temporary one and try with that)?

**Comment by bitfehler** [comment]
Closing, as I am assuming it's no longer an issue. Reopen if necessary.
