### ISSUE TITLE
Failed COPY ipmi_exporter from=builder 

### ISSUE THREAD

**Issue by ainamori** [soundcloud/ipmi_exporter#59]
Hi, I found that the Dockerfile needs to change "COPY --from=builder" due to as below.

##### ISSUE TYPE

 - Bug

##### HOW TO GET THE INFO

docker build . 
(or make docker)
 
##### SAMPLE COMMAND OUTPUT

```
--- snip ---
Setting up libfreeipmi16 (1.4.11-1.1ubuntu4.1) ...
Setting up libipmiconsole2 (1.4.11-1.1ubuntu4.1) ...
Setting up libipmidetect0 (1.4.11-1.1ubuntu4.1) ...
Setting up freeipmi-tools (1.4.11-1.1ubuntu4.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
Removing intermediate container f1a5395f3dd1
 ---> 91f8416c8110
Step 8/11 : COPY --from=builder /go/src/github.com/soundcloud/ipmi_exporter/ipmi_exporter /bin/ipmi_exporter
COPY failed: stat /var/lib/docker/overlay2/dd2f3f0e5d52053eb96a23e586d1e84c319276278249b16e7df6d462cf3f4f1c/merged/go/src/github.com/soundcloud/ipmi_exporter/ipmi_exporter: no such file or directory
ERROR: Job failed: exit code 1
```

##### CAUSE

go builder in docker makes ipmi_exporter as `ipmi-exporter`.

```
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
curl -s -L https://github.com/prometheus/promu/releases/download/v0.5.0/promu-0.5.0.linux-amd64.tar.gz | tar -xvzf - -C /tmp/tmp.3HO4rjwbn0
promu-0.5.0.linux-amd64/
promu-0.5.0.linux-amd64/promu
promu-0.5.0.linux-amd64/NOTICE
promu-0.5.0.linux-amd64/LICENSE
mkdir -p /go/bin
cp /tmp/tmp.3HO4rjwbn0/promu-0.5.0.linux-amd64/promu /go/bin/promu
rm -r /tmp/tmp.3HO4rjwbn0
>> building binaries
GO111MODULE=on /go/bin/promu build --prefix /go/src/github.com/soundcloud/ipmi_exporter 
 >   ipmi-exporter
>> running all tests
```

Note: go builder on CentOS (yum install golang) makes ipmi_exporter as `ipmi_exporter'. It seems only docker images.

### SOLUTION

Change filename.

**Comment by zogness** [comment]
I still can't build an image on CentOS. 
docker build -t "soundcloud/ipmi-exporter-linux-amd64:master" \
	-f ./Dockerfile \
	--build-arg ARCH="amd64" \
	--build-arg OS="linux" \
	./
Sending build context to Docker daemon  13.43MB
Step 1/10 : FROM quay.io/prometheus/golang-builder:1.15-base AS builder
 ---> f689514b8c6a
Step 2/10 : ADD . /go/src/github.com/soundcloud/ipmi_exporter/
 ---> Using cache
 ---> 9a6ed7f8c819
Step 3/10 : RUN cd /go/src/github.com/soundcloud/ipmi_exporter && make
 ---> Using cache
 ---> 27a12c3ce049
Step 4/10 : FROM ubuntu:18.04
 ---> c090eaba6b94
Step 5/10 : WORKDIR /
 ---> Using cache
 ---> e1cb074532a9
Step 6/10 : RUN apt-get update     && apt-get install freeipmi-tools -y --no-install-recommends     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f65aa4cd358b
Step 7/10 : COPY --from=builder /go/src/github.com/soundcloud/ipmi_exporter/ipmi-exporter /bin/ipmi_exporter
COPY failed: stat /var/lib/docker/overlay2/c765b216fa158c66792fa5e40eefb99a5f817fef318c7a7b1a0663249dab24b8/merged/go/src/github.com/soundcloud/ipmi_exporter/ipmi-exporter: no such file or directory
make: *** [Makefile.common:237: common-docker-amd64] Error 1

**Comment by ainamori** [comment]
> 
> 
> I still can't build an image on CentOS.
> docker build -t "soundcloud/ipmi-exporter-linux-amd64:master"
> -f ./Dockerfile
> --build-arg ARCH="amd64"
> --build-arg OS="linux"
> ./
> Sending build context to Docker daemon 13.43MB
> Step 1/10 : FROM quay.io/prometheus/golang-builder:1.15-base AS builder
> ---> f689514b8c6a
> Step 2/10 : ADD . /go/src/github.com/soundcloud/ipmi_exporter/
> ---> Using cache
> ---> 9a6ed7f8c819
> Step 3/10 : RUN cd /go/src/github.com/soundcloud/ipmi_exporter && make
> ---> Using cache
> ---> 27a12c3ce049
> Step 4/10 : FROM ubuntu:18.04
> ---> c090eaba6b94
> Step 5/10 : WORKDIR /
> ---> Using cache
> ---> e1cb074532a9
> Step 6/10 : RUN apt-get update && apt-get install freeipmi-tools -y --no-install-recommends && rm -rf /var/lib/apt/lists/*
> ---> Using cache
> ---> f65aa4cd358b
> Step 7/10 : COPY --from=builder /go/src/github.com/soundcloud/ipmi_exporter/ipmi-exporter /bin/ipmi_exporter
> COPY failed: stat /var/lib/docker/overlay2/c765b216fa158c66792fa5e40eefb99a5f817fef318c7a7b1a0663249dab24b8/merged/go/src/github.com/soundcloud/ipmi_exporter/ipmi-exporter: no such file or directory
> make: *** [Makefile.common:237: common-docker-amd64] Error 1

Hi, the go-builder also make the go binary as "ipmi_exporter" now.
Could you change the name in Dockerfile or see the PR please ?

**Comment by zogness** [comment]
Thanks. I changed every instance of ipmi-exporter to ipmi_exporter in the Makefile so my builds succeed however I can't run my image because it cannot find my config file.
time="2021-02-19T19:50:32Z" level=info msg="Starting ipmi_exporter" source="main.go:83"
time="2021-02-19T19:50:32Z" level=error msg="Error reading config file: open /ipmi_remote.yml: no such file or directory" source="config.go:99"
time="2021-02-19T19:50:32Z" level=fatal msg="Error parsing config file: open /ipmi_remote.yml: no such file or directory" source="main.go:87"

The last two lines of my Docker file read, 
ENTRYPOINT ["/bin/ipmi_exporter"]
CMD ["--config.file", "/ipmi_remote.yml"]

**Comment by ainamori** [comment]
Hi, did you see the docker-comose.yml ?
If you run the docker container by "docker run", you need to add config.yml into docker container or mount volume.

https://github.com/soundcloud/ipmi_exporter/blob/master/docker-compose.yml
