### ISSUE TITLE
ILO5 and ipmi

### ISSUE THREAD

**Issue by zrcorsica** [soundcloud/ipmi_exporter#61]
hello,

I would like to monitor hardware status of hp server with ipmi, but with ILO5 hp server I don't have disk status ! but I have these info with ILO4.

any idea ?

thank you

**Comment by bitfehler** [comment]
Hi there,

sorry, but the exporter itself has no influence on the metrics provided. In general, it exports whatever FreeIPMI delivers, which in turn depends on the support of your hardware's IPMI implementation.

As a first step, make sure you are using the latest version of FreeIPMI. If you still cannot get the disk status with that, your hardware provider's support would be a good address (if you have that). You could also try asking the FreeIPMI folks, they probably have a much better overview over what works and what doesn't.

Sorry, that's about all I can do for you, but this is simply outside of the scope of this exporter.
