### ISSUE TITLE
"dcmi"-scrape status "0" but data was gathered

### ISSUE THREAD

**Issue by hbokh** [soundcloud/ipmi_exporter#7]
*Vielen Dank* for this software in the first place! I started using this app. a week ago against Dell- and Supermicro-servers (and a cheap HPE Proliant at home).
With the recent commit `109c7ca` I see the DCMI-collector has status "0" after a scrape, where in fact is has gathered a value from the power consumption:

```txt
grep dcmi output-to-file
# HELP ipmi_dcmi_power_consumption_watts Current power consumption in Watts.
# TYPE ipmi_dcmi_power_consumption_watts gauge
ipmi_dcmi_power_consumption_watts 90
ipmi_up{collector="dcmi"} 0
```
Scraping with `ipmi-dcmi` confirms:

```txt
# ipmi-dcmi -h 10.11.12.13 -u user -p password -D LAN_2_0 -l user --get-system-power-statistics
Current Power                        : 90 Watts
Minimum Power over sampling duration : 10 watts
Maximum Power over sampling duration : 182 watts
Average Power over sampling duration : 89 watts
Time Stamp                           : 08/03/2018 - 13:15:03
Statistics reporting time period     : 1000 milliseconds
Power Measurement                    : Active
```

This behaviour is identical on both Dell and Supermicro.
From my point of view, the scrape is successful, but `ipmi_exporter` thinks not...
Any thoughts about this?

**Comment by bitfehler** [comment]
/me whistles nonchalantly...

Fixed a typo, thanks for reporting!
